### ISSUE TITLE
Interfaces should have virtual destructors

### ISSUE THREAD

**Issue by deanljohnson** [avirynd/UUV#1]
A+ job on the interview in my opinion.

Defining interfaces such as those in Drivers/Interfaces/Include should essentially always have a virtual destructor. If you do not add a virtual destructor, deleting a derived instance through a base class pointer will not call the derived destructor:

```
struct A { };

struct B : public A
{
~B() { printf("deleted"); }
};

A* aPtr = new B();
delete aPtr;
```

In this example, the destructor of B will not be called and "deleted" will not be logged.

Correct code:

```
struct A
{
virtual ~A() {}
};

struct B : public A
{
~B() override { printf("deleted"); }
};

A* aPtr = new B();
delete aPtr;
```

**Comment by avirynd** [comment]
Thank you for the feedback! Will fix this.

**Comment by avirynd** [comment]
Fixed in [latest commit](https://github.com/avirynd/UUV/commit/0045db00d69aaf1aa4f0abc5e439e78541215758).
